name: Release
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Tag if new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read version number
        id: read_toml
        uses: SebRollen/toml-action@v1.0.0
        with:
          file: Cargo.toml
          field: package.version
      - name: Set tag env variable
        run: echo IMAGE_TAG=v${{steps.read_toml.outputs.value}} >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: false
          tag: ${{ env.IMAGE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
